# Site settings
title: "Yash Kumar Sharma"
description: "Resume of Yash Kumar Sharma"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "false"
resume_name:                    "Yash Kumar Sharma"
resume_title:                   "Technical Lead - Web/Mobile"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "yks.nit@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "+91 8076074838"
resume_contact_address:         "D 83, Assotech Windsor Park, Indirapuram, Ghaziabad (U.P.)"

resume_header_contact_info:     "D 83, Assotech Windsor Park, Indirapuram, Ghaziabad (U.P.) • +91 8076074838 • yks.nit@gmail.com"
display_header_contact_info:    "false"

resume_header_intro: "<p>Developer, Architect and a Technical Lead with a passion for building problem-solving products using the best of technologies.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
# resume_section_recognition:     true
# resume_section_links:           true
# resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/yashkumarsharma"
  resume_twitter_url:           "https://twitter.com/_yash_sharma"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/yash-kumar-sharma-93ab4317"
  # resume_instagram_url:         "insert your Instagram URL here"
  # resume_website_url:           "http://joelglovier.com"
  # resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
